name = "Juls"
uuid = "56019723-2d87-4a65-81ff-59d5d8913e3c"
authors = ["Milan Kloewer"]
version = "0.5.0"

[compat]
julia = "1"
Parameters = "^0.12"
NetCDF = "^0.8"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
